// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @notice Supported oracle backends for ownership proof generation.
enum OracleType {
    TEE,
    ZKP
}

/// @notice Proof submitted by the receiver (or their delegate) expressing intent
///         to receive the data key.
/// @dev AccessProof does not carry OracleType because receiver-side signing is
///      independent of the oracle backend used to prove data ownership.
///      Signed payload: keccak256(abi.encodePacked(dataHash, targetPubkey, nonce, deadline)).
struct AccessProof {
    bytes32 dataHash;
    /// @dev Empty means the receiver's Ethereum public key is used (see wantedKey semantics).
    bytes   targetPubkey;
    bytes   nonce;
    /// @dev Unix timestamp after which the proof is rejected. Together with `nonce`
    ///      this gates replay protection — see NonceRegistryUpgradeable.
    uint256 deadline;
    bytes   proof;
}

/// @notice Ownership proof generated by a TEE or ZKP oracle.
/// @dev Encoding of `sealedKey` and `proof` depends on `oracleType`.
///      Signed payload (TEE): keccak256(abi.encodePacked(dataHash, sealedKey, targetPubkey, nonce, deadline)).
struct OwnershipProof {
    OracleType oracleType;
    bytes32    dataHash;
    bytes      sealedKey;
    bytes      targetPubkey;
    bytes      nonce;
    /// @dev Unix timestamp after which the proof is rejected.
    uint256    deadline;
    bytes      proof;
}

struct TransferValidityProof {
    AccessProof    accessProof;
    OwnershipProof ownershipProof;
}

/// @notice Output returned by the verifier after successful proof validation.
/// @dev wantedKey semantics (derived from AccessProof.targetPubkey):
///      - Empty   : receiver uses their Ethereum key; caller must verify
///                  keccak256(targetPubkey) maps to the `to` address.
///      - Non-empty: receiver uses a custom encryption key; caller must verify
///                  targetPubkey == wantedKey.
///      oracleType is included so downstream consumers (contracts or indexers)
///      know how to interpret sealedKey without re-inspecting the input proof.
struct TransferValidityProofOutput {
    OracleType oracleType;
    bytes32    dataHash;
    bytes      sealedKey;
    bytes      targetPubkey;
    bytes      wantedKey;
    address    accessAssistant;
    bytes      accessProofNonce;
    bytes      ownershipProofNonce;
}

interface IERC7857DataVerifier {
    /// @notice Verify that each (AccessProof, OwnershipProof) pair proves:
    ///         1. The data identified by dataHash is accessible to the target receiver.
    ///         2. The data is owned by the current sender.
    ///         3. The data key is re-encrypted and delivered via sealedKey.
    ///
    /// @dev Proof ordering: proofs[i] must correspond to the i-th IntelligentData entry
    ///      of the token. The caller (ERC7857 contract) is responsible for this ordering.
    ///
    ///      State writes: implementations MAY write state for replay prevention (e.g.
    ///      recording used nonces). Implementations MUST NOT transfer tokens, emit
    ///      ERC721 events, or modify storage outside their own bookkeeping namespace.
    ///
    /// @param proofs One proof per IntelligentData entry, ordered identically to the
    ///               token's intelligentDatasOf() array.
    function verifyTransferValidity(
        TransferValidityProof[] calldata proofs
    ) external returns (TransferValidityProofOutput[] memory);
}
